

# IMPORT
import time

# ASCii print functions

def print_mastermind():
    print("___  ___  ___   _____ _____ ______________  ________ _   _______  ")
    time.sleep(.2)
    print("|  \/  | / _ \ /  ___|_   _|  ___| ___ \  \/  |_   _| \ | |  _  \ ")
    time.sleep(.2)
    print("| .  . |/ /_\ \\ `--.   | | | |__ | |_/ / .  . | | | |  \| | | | | ")
    time.sleep(.2)
    print("| |\/| ||  _  | `--. \ | | |  __||    /| |\/| | | | | . ` | | | | ")
    time.sleep(.2)
    print("| |  | || | | |/\__/ / | | | |___| |\ \| |  | |_| |_| |\  | |/ /  ")
    time.sleep(.2)
    print("\_|  |_/\_| |_/\____/  \_/ \____/\_| \_\_|  |_/\___/\_| \_/___/   ")
    time.sleep(.2)
    print("")
    time.sleep(.2)
    print(" _            ")
    time.sleep(.2)
    print("| |           ")
    time.sleep(.2)
    print("| |__  _   _  ")
    time.sleep(.2)
    print("| '_ \| | | | ")
    time.sleep(.2)
    print("| |_) | |_| | ")
    time.sleep(.2)
    print("|_.__/ \__, | ")
    time.sleep(.2)
    print("        __/ | ")
    time.sleep(.2)
    print("       |___/  ")
    time.sleep(.2)
    print("")
    time.sleep(.2)
    print("___  ____ _          _____  ")
    time.sleep(.2)
    print("|  \/  (_) |        |  __ \ ")
    time.sleep(.2)
    print("| .  . |_| | _____  | |  \/ ")
    time.sleep(.2)
    print("| |\/| | | |/ / _ \ | | __  ")
    time.sleep(.2)
    print("| |  | | |   <  __/ | |_\ \ ")
    time.sleep(.2)
    print("\_|  |_/_|_|\_\___|  \____/ ")
    time.sleep(.2)
    print("\n\n")
    
    
def you_win():
    print("__   _______ _   _   _    _ _____ _   _ _  ")
    time.sleep(.2)
    print("\ \ / /  _  | | | | | |  | |_   _| \ | | | ")
    time.sleep(.2)
    print(" \ V /| | | | | | | | |  | | | | |  \| | | ")
    time.sleep(.2)
    print("  \ / | | | | | | | | |/\| | | | | . ` | | ")
    time.sleep(.2)
    print("  | | \ \_/ / |_| | \  /\  /_| |_| |\  |_| ")
    time.sleep(.2)
    print("  \_/  \___/ \___/   \/  \/ \___/\_| \_(_) ")
    time.sleep(.2)
    print("")